import type {SidebarsConfig} from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentationSidebar: [
    'intro',
    'understanding-eutxos',
    {
      type: 'category',
      label: 'Language reference',
      link: {
        type: 'generated-index',
      },
      items: [
        'language-reference/comments',
        'language-reference/variables',
        'language-reference/primitives',
        'language-reference/containers',
        'language-reference/control-flow',
        'language-reference/functions',
        'language-reference/structs',
        'language-reference/enums',
        'language-reference/destructuring',
        'language-reference/automatic-methods',
        'language-reference/operators',
        'language-reference/generics',
        'language-reference/validators',
        'language-reference/modules',
        {
          type: 'category',
          label: 'Builtins',
          link: {type: 'doc', id: 'language-reference/builtins/index'},
          items: [
            'language-reference/builtins/address',
            'language-reference/builtins/any',
            'language-reference/builtins/assetclass',
            'language-reference/builtins/bool',
            'language-reference/builtins/bytearray',
            'language-reference/builtins/credential',
            'language-reference/builtins/data',
            'language-reference/builtins/datumhash',
            'language-reference/builtins/dcert',
            'language-reference/builtins/duration',
            'language-reference/builtins/int',
            'language-reference/builtins/list',
            'language-reference/builtins/map',
            'language-reference/builtins/mintingpolicyhash',
            'language-reference/builtins/option',
            'language-reference/builtins/outputdatum',
            'language-reference/builtins/pubkey',
            'language-reference/builtins/pubkeyhash',
            'language-reference/builtins/real',
            'language-reference/builtins/scriptcontext',
            'language-reference/builtins/scripthash',
            'language-reference/builtins/scriptpurpose',
            'language-reference/builtins/stakingcredential',
            'language-reference/builtins/stakinghash',
            'language-reference/builtins/stakingpurpose',
            'language-reference/builtins/stakingvalidatorhash',
            'language-reference/builtins/string',
            'language-reference/builtins/time',
            'language-reference/builtins/timerange',
            'language-reference/builtins/tx',
            'language-reference/builtins/txid',
            'language-reference/builtins/txinput',
            'language-reference/builtins/txoutput',
            'language-reference/builtins/txoutputid',
            'language-reference/builtins/validatorhash',
            'language-reference/builtins/valuable',
            'language-reference/builtins/value'
          ]
        }
      ]
    }
    //{type: 'autogenerated', dirName: '.'}
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
