import type {SidebarsConfig} from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  learnSidebar: [
    {type: 'autogenerated', dirName: 'learn'}
  ],
  languageSidebar: [
    {type: 'autogenerated', dirName: 'lang'}
  ],
  sdkSidebar: [
    {type: 'autogenerated', dirName: 'sdk'}
  ],
  irisSidebar: [
    {type: 'autogenerated', dirName: 'iris'}
  ]
};

export default sidebars;
